//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponyRule
    {
        public int Id { get; set; }
        public string roledescription { get; set; }
        public Nullable<long> IdUserInsert { get; set; }
        public Nullable<long> IdUserDelete { get; set; }
        public Nullable<long> IdUserUpdate { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public Nullable<bool> StateDelete { get; set; }
    }
}
