//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.customerchangepass = new HashSet<customerchangepass>();
            this.CustomerProduct = new HashSet<CustomerProduct>();
            this.CustomerProjectTicket = new HashSet<CustomerProjectTicket>();
            this.factor = new HashSet<factor>();
            this.Payment = new HashSet<Payment>();
        }
    
        public long Id { get; set; }
        public string FullName { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public System.DateTime DateInsert { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public bool Statedelete { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string userimage { get; set; }
        public string PostalCode { get; set; }
        public string NationalCode { get; set; }
        public string NationalID { get; set; }
        public string EconomicCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerchangepass> customerchangepass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProduct> CustomerProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerProjectTicket> CustomerProjectTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factor> factor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
