//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProduct
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long ProductId { get; set; }
        public System.DateTime DateRequest { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public Nullable<System.DateTime> DateRespond { get; set; }
        public string Description { get; set; }
        public string ResonOfCancelletion { get; set; }
        public int IdState { get; set; }
        public Nullable<long> Count { get; set; }
        public Nullable<long> TotalPrice { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public Nullable<bool> StateDelete { get; set; }
        public string factorcod { get; set; }
        public string resonofnotconfirm { get; set; }
        public string PaymentFactoreCode { get; set; }
        public string SaleRefrence { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual StateCustomerProduct StateCustomerProduct { get; set; }
    }
}
