//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class discountcode
    {
        public long id { get; set; }
        public string dicountcode { get; set; }
        public int discountpersent { get; set; }
        public System.DateTime dateinsert { get; set; }
        public System.DateTime dateende { get; set; }
        public Nullable<int> numberofuseg { get; set; }
        public Nullable<long> customerid { get; set; }
    }
}
