//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factor
    {
        public long Id { get; set; }
        public string factorcode { get; set; }
        public System.DateTime dateinsert { get; set; }
        public Nullable<System.DateTime> dateupdate { get; set; }
        public Nullable<System.DateTime> datedelete { get; set; }
        public long prcount { get; set; }
        public long customerId { get; set; }
        public string discountcode { get; set; }
        public Nullable<int> discountpercent { get; set; }
        public bool statedelete { get; set; }
        public long totalprice { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
