//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_companies
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string CooperationText { get; set; }
        public string ActivityText { get; set; }
        public string Link { get; set; }
        public string image { get; set; }
    }
}
