//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long Id { get; set; }
        public string RefrenceNumber { get; set; }
        public Nullable<long> SaleRefrence { get; set; }
        public string StatusPayment { get; set; }
        public Nullable<bool> PaymentFinish { get; set; }
        public Nullable<long> Amount { get; set; }
        public string BankName { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<System.DateTime> BuyDatetime { get; set; }
        public string StatusCode { get; set; }
        public string StatusMessag { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
