//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSuggestion
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string SuggestionText { get; set; }
        public int rank { get; set; }
        public System.DateTime dateinsert { get; set; }
        public Nullable<System.DateTime> dateupdate { get; set; }
        public Nullable<System.DateTime> datedelete { get; set; }
        public bool statedelete { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
