//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperty
    {
        public long Id { get; set; }
        public long IdProduct { get; set; }
        public long IdProperty { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> Date_Insert { get; set; }
        public Nullable<long> IdUser_Insert { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
        public Nullable<long> IdUser_Update { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<long> IdUser_Delete { get; set; }
        public Nullable<bool> StateDelete { get; set; }
        public Nullable<long> Idsort { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Property Property { get; set; }
    }
}
