//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlidShow
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
        public Nullable<long> Idsort { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> IdUserInsert { get; set; }
        public Nullable<int> IdUserUpdate { get; set; }
        public Nullable<int> IduserDelete { get; set; }
        public bool StateDelete { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public string Title { get; set; }
    }
}
