//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiperStar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string respondmessag { get; set; }
        public System.DateTime dateinsert { get; set; }
        public Nullable<System.DateTime> datedelete { get; set; }
        public Nullable<System.DateTime> daterespond { get; set; }
        public bool statedelete { get; set; }
    }
}
